// UserModel.js - Prisma Schema is defined in prisma/schema.prisma
// This file serves as a reference for User operations using Prisma Client
// The User model is automatically generated by Prisma based on the schema

// Import Prisma Client
import prisma from "../config/prisma.js";

// User operations are now handled through Prisma Client
// Example: await prisma.user.findUnique({ where: { email: "user@example.com" } })
// See UserService.js for implemented queries

export default prisma.user;
